import 'entity/post_entity.dart';

final dummyPosts = [
  // ───── 코디 질문 (question) ─────
  Post(
    id: 'q1',
    title: '흰 셔츠엔 무슨 바지가 좋을까요?',
    content: '깔끔한 흰 셔츠에 어울리는 바지 추천해주세요.',
    category: PostCategory.question,
    productId: 201,
    likeCount: 3,
    commentCount: 1,
    createAt: DateTime.now().subtract(Duration(hours: 1)),
  ),
  Post(
    id: 'q2',
    title: '여름 반바지 코디 질문!',
    content: '반바지 입고 상의는 뭘 입는 게 좋을까요?',
    category: PostCategory.question,
    productId: 202,
    likeCount: 6,
    commentCount: 2,
    createAt: DateTime.now().subtract(Duration(hours: 5)),
  ),
  Post(
    id: 'q3',
    title: '청자켓 어울리는 이너 추천 좀!',
    content: '청자켓에 안에 뭐 입는 게 괜찮을까요?',
    category: PostCategory.question,
    productId: null,
    likeCount: 2,
    commentCount: 0,
    createAt: DateTime.now().subtract(Duration(days: 1)),
  ),
  Post(
    id: 'q4',
    title: '운동화 추천해주세요!',
    content: '요즘 깔끔한 흰색 운동화 뭐가 좋나요?',
    category: PostCategory.question,
    productId: 203,
    likeCount: 9,
    commentCount: 3,
    createAt: DateTime.now().subtract(Duration(days: 1, hours: 2)),
  ),
  Post(
    id: 'q5',
    title: '겨울 코트 고민이에요',
    content: '롱코트랑 숏패딩 중 뭐가 더 괜찮을까요?',
    category: PostCategory.question,
    productId: null,
    likeCount: 4,
    commentCount: 2,
    createAt: DateTime.now().subtract(Duration(days: 2)),
  ),

  // ───── 코디 추천 (recommend) ─────
  Post(
    id: 'r1',
    title: '요즘 핫한 여름룩!',
    content: '린넨 셋업 코디 추천해요.',
    category: PostCategory.recommend,
    productId: 301,
    likeCount: 15,
    commentCount: 4,
    createAt: DateTime.now().subtract(Duration(hours: 6)),
  ),
  Post(
    id: 'r2',
    title: '모던 캐주얼 코디 추천',
    content: '검은 티 + 연청바지 조합 최고!',
    category: PostCategory.recommend,
    productId: null,
    likeCount: 10,
    commentCount: 1,
    createAt: DateTime.now().subtract(Duration(days: 1, hours: 1)),
  ),
  Post(
    id: 'r3',
    title: '데이트룩 추천해요!',
    content: '하늘색 셔츠에 면바지 조합 어때요?',
    category: PostCategory.recommend,
    productId: 302,
    likeCount: 11,
    commentCount: 5,
    createAt: DateTime.now().subtract(Duration(days: 2)),
  ),
  Post(
    id: 'r4',
    title: '꾸안꾸 코디 추천',
    content: '편안하면서도 멋스러운 무드의 코디예요.',
    category: PostCategory.recommend,
    productId: null,
    likeCount: 7,
    commentCount: 2,
    createAt: DateTime.now().subtract(Duration(days: 3)),
  ),
  Post(
    id: 'r5',
    title: '여친이 좋아한 룩 ㅎㅎ',
    content: '스트라이프 셔츠 + 베이지 팬츠 강추!',
    category: PostCategory.recommend,
    productId: 303,
    likeCount: 20,
    commentCount: 6,
    createAt: DateTime.now().subtract(Duration(days: 4)),
  ),

  // ───── My+ (내 글) ─────
  Post(
    id: 'm1',
    title: '오늘 코디 어땠나요?',
    content: '올블랙 코디 해봤어요.',
    category: PostCategory.my,
    productId: 401,
    likeCount: 5,
    commentCount: 1,
    createAt: DateTime.now().subtract(Duration(hours: 2)),
  ),
  Post(
    id: 'm2',
    title: '주말 데일리룩 공유!',
    content: '라운지웨어 입고 한강 갔어요~',
    category: PostCategory.my,
    productId: null,
    likeCount: 3,
    commentCount: 0,
    createAt: DateTime.now().subtract(Duration(days: 1)),
  ),
  Post(
    id: 'm3',
    title: '회사 출근룩 공유',
    content: '포멀하게 입은 날!',
    category: PostCategory.my,
    productId: 402,
    likeCount: 6,
    commentCount: 2,
    createAt: DateTime.now().subtract(Duration(days: 1, hours: 5)),
  ),
  Post(
    id: 'm4',
    title: '오늘 셀카 + 코디',
    content: '무채색으로 깔맞춤!',
    category: PostCategory.my,
    productId: null,
    likeCount: 2,
    commentCount: 0,
    createAt: DateTime.now().subtract(Duration(days: 2)),
  ),
  Post(
    id: 'm5',
    title: '마지막 날 룩!',
    content: '스카프와 함께 포인트 준 코디예요.',
    category: PostCategory.my,
    productId: 403,
    likeCount: 9,
    commentCount: 1,
    createAt: DateTime.now().subtract(Duration(days: 3)),
  ),
];
